# Uncomment the next line to define a global platform for your project
# platform :ios, '15.0'

target 'FeeManager' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FeeManager
	pod 'FirebaseAnalytics'
	pod 'FirebaseAuth'
	pod 'FirebaseFirestore'
	pod 'FirebaseStorage'
	pod 'FirebaseDatabase'
	pod 'FirebaseUI'
	pod 'RNCryptor', '~> 5.0'

end
